Re-based version of #132
ros-industrial/motoman pull request #133
Opened 2016-10-21 01:12 UTC by shaun-edwards

Attempting to create a clean PR of #132.  This version has not been re-built with MotoPlus.

2016-10-21 08:34 UTC, gavanderhoorn requested changes
I realise this is Shaun's rebased version, but the original PR contains the same changes.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +			}
These lines now use spaces for indentation, where the rest of the file uses tabs.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/CtrlGroup.c
> +	    torqueValues[i] = (double)dst_trq.data[ctrlGroup->groupId][i] * 0.000001; //Use double.  Float only good for 6 sig digits.
Perhaps use `1e-6`?

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/CtrlGroup.h
> +	long prevPulsePos[MAX_PULSE_AXES];			// The commanded pulse position that the trajectory starts at (Ros_MotionServer_StartTrajMode)
Indentation.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +          	ret = Ros_MotionServer_SimpleMsgProcess(controller, &receiveMsg, expectedSize, &replyMsg);
Indentation

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +        	break;	// Close the connection
spaces vs tabs again.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +	if (alarmstatus.sIsAlarm & 0x02) //alarm is active
Could we perhaps avoid the magic nr (`0x02`)? A local `#define` or `const` would be nicer.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +	if (alarmstatus.sIsAlarm & 0x01) //error is active
Magic nr again.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +		if( controller->ctrlGroups[grpNo] != NULL /*&& Ros_CtrlGroup_IsRobot(controller->ctrlGroups[grpNo])*/)
Should commented code be removed? Otherwise add comment why it should be retained.

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +	//long prevPulsePos[MP_GRP_AXES_NUM];
Commented code?

2016-10-21 08:34 UTC, gavanderhoorn commented on motoman_driver/MotoPlus/MotionServer.c
> +	//Ros_CtrlGroup_ConvertToMotoPos(ctrlGroup, curTrajData->pos, controller->prevPulsePos);
Commented again.

2016-10-25 12:56 UTC, ted-miller commented
@shaun-edwards 
This version in the "ted-miller-indigo-devel branch on shaun-edwards/motoman" is way behind.  It's missing all the DX200 stuff.

I've made all the requested changes and pushed to 
https://github.com/ros-industrial/motoman/tree/pr/133

Hopefully you can do some git magic to merge that into something useful.  I'm "gitting" really confused. (Yes, I amuse myself)

2016-11-05 11:58 UTC, gavanderhoorn commented
Perhaps we could help out in situations like this in the future by requesting that contributors enable *Allow edits from maintainers*.

I ticketed this over at ros-industrial/ros_industrial_issues#43.

2016-11-07 12:57 UTC, shaun-edwards commented
@ted-miller, friendly ping.

2016-11-07 13:59 UTC, ted-miller commented
@shaun-edwards  As I mentioned in the previous comment, this version you have is very outdated.  I tried to just update everything in your branch, but I get a failure (see attached screenshot).
![failure](https://cloud.githubusercontent.com/assets/4623811/20060244/423fb096-a4c8-11e6-894d-4c0060bec13e.png)


So, I have pushed the latest updates to https://github.com/ros-industrial/motoman/tree/pr/133
Can you work with that?  Or do I need to do something else?

2016-11-07 14:03 UTC, gavanderhoorn commented
Diff with `indigo-devel`: [here](https://github.com/ros-industrial/motoman/compare/indigo-devel...pr/133).

2016-11-29 03:03 UTC, shaun-edwards commented
PR #136 created.

2016-11-29 03:03 UTC, closed without merging