Bug fix: JointTrajectoryAction for Dual Arm FS100
ros-industrial/motoman pull request #135
Opened 2016-11-20 09:01 UTC by qqfly

JointTrajectoryAction can now handle correctly cases where a single trajectory containing all robots (2 arms 2 torsos) of motoman is used. This is only vertified on Motoman SDA5F.

Before this fix the state of the robot changed at "LOST"(with error code: Transitioning goal to LOST) after some seconds and the trajectory was aborted.
This issue was discussed in [mail-lists](https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/svtmTaMwqx0) and PR #79 .

2016-11-21 14:53 UTC, shaun-edwards commented
@qqfly thanks for the pr. I'll take a look in the next  couple of days.

2016-11-28 05:42 UTC, qqfly commented
friendly ping.

2016-11-29 03:22 UTC, shaun-edwards requested changes
@qqfly, i've got a few questions on the change you proposed (see review comments).

2016-11-29 03:22 UTC, shaun-edwards commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
What do you mean by this comment?

2016-11-29 03:22 UTC, shaun-edwards commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +    // joint torso_joint_b2 is not in traj.joint_names, so the last group is ignored here.
Is this comment related to the issue above?

2016-11-29 03:22 UTC, shaun-edwards commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  sub_trajectory_state_all_  = this->node_.subscribe<control_msgs::FollowJointTrajectoryFeedback>("/feedback_states", 1,
Is this subscriber different than the one [here](https://github.com/ros-industrial/motoman/pull/135/files#diff-dbbdafd73ea4190550a2bc504ba53f24R87)

2016-11-29 06:41 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  sub_trajectory_state_all_  = this->node_.subscribe<control_msgs::FollowJointTrajectoryFeedback>("/feedback_states", 1,
subscriber **_sub_trajectory_state__** listen to single group feedback, for example **_*/arm_left/feedback_states_** and **_*/arm_right/feedback_states_**;
but when we execute a multi-groups motion, such as group "arms" ( = "arm_left" + "arm_right"), we should listen to  **_/feedback_states_** for all joints.
The origin code ignores feedback of multi-groups motion, and the robot state "LOST".
In this PR, I create a new subscriber **_sub_trajectory_state_all__** to fix this problem.

2016-11-29 06:52 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
There are four groups (not MoveGroup) for SDA dual arm robot (arm_left, arm_right, torso_1, torso_2), and torso_1 and torso_2 share a same joint (torso_joint).
for **_all_joint_names__**, there are 16 joints (7 left + 7 right + torso_joint_b1 + torso_joint_b2)
while **_msg->joint_names_** only have 15 joints (7 left + 7 right + torso_joint_b1), torso_joint_b2 is missing.
so **_industrial_utils::isSimilar()_** always return false in this scene.

2016-11-29 06:55 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +    // joint torso_joint_b2 is not in traj.joint_names, so the last group is ignored here.
Yes, this is the same with the issue above.
we only use the first 3 groups value, and ignore the last torso_joint_b2 (**last_trajectory_state_map_.size()** ).

2016-11-29 07:54 UTC, gavanderhoorn commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
@qqfly: the driver is also used for non-dual-arm robots. This logic will not work there, as the 'shared joint' is a peculiarity of how dual-arm robots are configured.

2016-11-29 07:57 UTC, gavanderhoorn commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +    // joint torso_joint_b2 is not in traj.joint_names, so the last group is ignored here.
See my earlier comment: ignoring the last group is not a good idea on systems that actually do have 4 groups, but do not have the special joint<->group mapping that the SDA series has.

2016-11-29 08:05 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
@gavanderhoorn , for single-arm robots, this function _JointTrajectoryAction::controllerStateCB(
  const control_msgs::FollowJointTrajectoryFeedbackConstPtr &msg)_ will not be called, it will turn to _JointTrajectoryAction::controllerStateCB(
  const control_msgs::FollowJointTrajectoryFeedbackConstPtr &msg, **int robot_id**)_
I have cout this two kind of joint_names when connecting with my SDA5F, there is no torso_joint_b2 in msg->joint_names. That's why I comment out this joint name checking.

2016-11-29 08:06 UTC, gavanderhoorn commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
Single arm, but multi-group robots are also targeted by this driver.

2016-11-29 08:24 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
Got it.
But for SDA-series robot (4-groups), this problem is still there, (all_joint_names_ isn't consistent with _msg->joint_names), and the joint_name checking or goal-constraint checking fails. The same with the issue below.
Maybe we can only do this for SDA-series robots?

2016-11-29 08:24 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
Got it.
But for SDA-series robot (4-groups), this problem is still there, (all_joint_names_ isn't consistent with _msg->joint_names), and the joint_name checking or goal-constraint checking fails. The same with the issue below.
Maybe we can only do this for SDA-series robots?

2016-12-22 18:06 UTC, shaun-edwards commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
Sorry for the delay on my part, but I'm in agreement with @gavanderhoorn.  Any solution should be independent of the robot type.  I can't think of a bulletproof way of knowing the robot type.  I don't fully understand why the message doesn't have `torso_joint_b2`.  Is the answer to just fix the `msg->joint_names` publisher?

2016-12-23 02:57 UTC, qqfly commented on motoman_driver/src/industrial_robot_client/joint_trajectory_action.cpp
> +  // joint torso_joint_b2 is not in msg->joint_names, so this code is commented out.
yes, it would be much better. I will firstly vertify this bug (publisher for dual-arm robots), after a couple of days.

2017-03-17 19:48 UTC, shaun-edwards commented
Closing this issue...if this is still an active PR, please feel free to comment with more information and we will reopen it.

2017-03-17 19:48 UTC, closed without merging