CI Update
ros-industrial/motoman pull request #305
Opened 2019-11-06 15:38 UTC by marip8

CI for the ROS Kinetic shadow-fixed repository is currently broken by a few MoveIt packages. This PR updates the CI config to ignore failures in shadow-fixed repositories

2019-11-08 17:09 UTC, gavanderhoorn commented
If this is a known issue with the testing repositories, which I assume will be fixed, should we update CI now to work around that?

2019-11-08 17:46 UTC, marip8 commented
I think this PR is still valid because the allowed failures matrix was ignored by Travis (see [this build](https://travis-ci.com/ros-industrial/motoman/builds/135288335) before the changes in this PR). I've also added a CI test for Melodic for what it's worth. Also, despite being somewhat inconsequential, it doesn't look great that the main page shows this repository failing CI

2019-11-08 17:56 UTC, gavanderhoorn commented
> I think this PR is still valid because the allowed failures matrix was ignored by Travis (see [this build](https://travis-ci.com/ros-industrial/motoman/builds/135288335) before the changes in this PR).

I'm not sure I understand: are you referring to the fact that there was no entry for `kinetic` in allowed failures?

> I've also added a CI test for Melodic for what it's worth.

That is a nice addition.

> Also, despite being somewhat inconsequential, it doesn't look great that the main page shows this repository failing CI

It would still not fix the ROS buildfarm build badge, but ok.

---

Could I ask you to split the PR into separate commits? Something like this:

 1. remove the `sudo` and `dist` keys
 1. add `services: [docker]`
 1. add `kinetic+ros-shadow-fixed` to allowed failures
 1. add `melodic` rows
 1. switch `ros-shadow-fixed` to `ros-testing`

2019-11-08 17:57 UTC, gavanderhoorn requested changes
Could I ask you to split the PR into separate commits? Something like this:

 1. remove the `sudo` and `dist` keys
 1. add `services: [docker]`
 1. add `kinetic+ros-shadow-fixed` to allowed failures
 1. add `melodic` rows
 1. switch `ros-shadow-fixed` to `ros-testing`

2019-11-08 19:14 UTC, marip8 commented
>> I think this PR is still valid because the allowed failures matrix was ignored by Travis (see this build before the changes in this PR).
>
> I'm not sure I understand: are you referring to the fact that there was no entry for kinetic in allowed failures?

There was no entry for Kinetic; also Travis did not treat the Indigo `ros-shadow-fixed` builds as allowed failures because the entries in `allowed_failures` did not match the lines in `matrix` (at least changing that seemed to fix the issue)

>> Also, despite being somewhat inconsequential, it doesn't look great that the main page shows this repository failing CI
>
> It would still not fix the ROS buildfarm build badge, but ok.

The intent was to fix the Travis build badge; I didn't realize one of the badges points to the buildfarm

2019-11-12 16:11 UTC, gavanderhoorn approved these changes

2019-11-12 16:12 UTC, merged

2019-11-12 16:13 UTC, gavanderhoorn commented
Thanks @marip8 :+1: 

This won't fix the buildfarm badge, but the Travis one should now be green again.

We should probably see whether we'd want to revert any of the allowed-failure additions when/if the regressions get fixed.