ES165RDII Support
ros-industrial/motoman pull request #348
Opened 2020-07-30 14:55 UTC by marip8

Initial commit for the ES165RDII robot with contributions from @gavanderhoorn

2020-07-30 17:04 UTC, gavanderhoorn requested changes
Looks OK.

Two in-line suggestions.

2020-07-30 17:04 UTC, gavanderhoorn commented on motoman_es_support/package.xml
> +  <url type="repository">https://github.com/ros-industrial/motoman_experimental</url>
```suggestion
  <url type="bugtracker">https://github.com/ros-industrial/motoman/issues</url>
  <url type="repository">https://github.com/ros-industrial/motoman</url>
```

2020-07-30 17:04 UTC, gavanderhoorn commented on motoman_es_support/package.xml
> +  <url type="website">http://wiki.ros.org/motoman_es165rdii_support</url>
```suggestion
  <url type="website">http://wiki.ros.org/motoman_es_support</url>
```

2020-07-30 19:15 UTC, gavanderhoorn commented on motoman_es_support/launch/load_es165rdii.launch
> +  <param name="robot_description" command="$(find xacro)/xacro.py --inorder '$(find motoman_es_support)/urdf/es165rdii.xacro'" />
```suggestion
  <param name="robot_description" command="$(find xacro)/xacro --inorder '$(find motoman_es_support)/urdf/es165rdii.xacro'" />
```

2020-07-31 14:32 UTC, marip8 commented
Given the discussion in #349 which indicates that robot geometry does not typically change between controller variants of a robot, should I re-title these files to something that is not controller specific (i.e. ES165R) and provide controller-specific joint velocity limits?

2020-10-05 17:19 UTC, gavanderhoorn commented
> Given the discussion in #349 which indicates that robot geometry does not typically change between controller variants of a robot, should I re-title these files to something that is not controller specific (i.e. ES165R) and provide controller-specific joint velocity limits?

We could, but without using a `.yaml` file I don't see how we would do this in a nice and scalable way.

Would you have any idea immediately?

Otherwise let's not complicate things any further.

2020-10-05 21:01 UTC, marip8 commented
It wasn't too difficult to implement the YAML files for the specific controller velocity limits. They get loaded into the URDF via launch files where the user specifies the `controller` argument to find the controller-specific file. Let me know what you think of this approach

2021-09-28 17:15 UTC, marip8 commented
@gavanderhoorn friendly ping

2021-09-29 15:28 UTC, gavanderhoorn approved these changes

2021-09-29 15:29 UTC, gavanderhoorn commented
Thanks for the PR @marip8, appreciated.

Apologies for the delayed merge.

It might be nice to add some convenience `.launch` files which provide the correct argument for `controller`. They could be named after the variant. But we don't need to do that now.

2021-09-29 15:30 UTC, merged