Add gp8 opw
ros-industrial/motoman pull request #493
Opened 2022-04-13 09:57 UTC by cjue

* add opw file
* fix link2 collision mesh
* add flange link
* update reference documentation
* minor fix for velocity limits

2025-02-08 10:38 UTC, gavanderhoorn commented
@cjue: I submitted isys-vision/motoman#6 to add 132d728f2b126c4ffda485e2e8883c4e9d3049b2. Please review and merge.

2025-02-08 10:39 UTC, gavanderhoorn commented on motoman_gp8_support/meshes/collision/gp8_link_2_l.stl
Is this a downsampled version of the `visual` mesh?

(just noticed the `visual` mesh is 1MB+. Not sure what happened during the review when that was initially contributed ..)

2025-02-08 10:59 UTC, gavanderhoorn requested changes
Marking as *requested changes*.

2025-02-10 13:50 UTC, EricMarcil commented on motoman_gp8_support/meshes/collision/gp8_link_2_l.stl
That might have been from a 3D model that included a lot of internal elements which makes if harder reduce but still keep details. I should be able to generate new .dae model by converting MotoSim models that are already reduced. 
@gavanderhoorn Do you want me to do it on this PR, or it's probably better to create a separate PR?

2025-02-10 14:02 UTC, gavanderhoorn commented on motoman_gp8_support/meshes/collision/gp8_link_2_l.stl
No, no need.

It's already in the history of the repository, so adding a newer version will not reduce the total size.

2025-02-11 14:31 UTC, cjue commented
> @cjue: I submitted [isys-vision#6](https://github.com/isys-vision/motoman/pull/6) to add [132d728](https://github.com/ros-industrial/motoman/commit/132d728f2b126c4ffda485e2e8883c4e9d3049b2). Please review and merge.

done

2025-02-13 12:16 UTC, gavanderhoorn approved these changes

2025-02-13 12:17 UTC, merged

2025-02-13 12:17 UTC, gavanderhoorn commented
Thanks @cjue :+1: