Add gp7 opw
ros-industrial/motoman pull request #500
Opened 2022-05-24 13:39 UTC by cjue

* add opw file
* fix link2 collision mesh
* add flange link
* update reference documentation
* minor fix for velocity limits
* rename and refactor test

2022-05-24 13:47 UTC, cjue commented
Sidenote: somehow all of the technical drawings and tables I could find for the GP7 are missing the height offset from base_link to link_1_s. According to the current URDF it's identical to the values for GP4 and GP8, which sounds reasonable.

https://www.yaskawa.eu.com/Global%20Assets/Downloads/Brochures_Catalogues/Robotics/MOTOMAN_Robots/GP-Series/Flyer_Robot_GP7_E_10.2021.pdf

2022-05-24 20:49 UTC, EricMarcil commented
@cjue I'm surprise that the dimension is missing from the drawing.  I can confirm that the distance is 330mm.  If you ever need to look-up that distance for other robots, the MotoSim manual has them all listed in the chapter 15.9:
[MotoSimEG-VRC manual](https://www.motoman.com/getmedia/e0644ab4-e22b-4a40-8be8-ac6c222b1990/156225-1CD.pdf.aspx?ext=.pdf)

2022-05-25 08:39 UTC, cjue commented
Thank you for that hint

2025-02-08 10:57 UTC, gavanderhoorn commented
@cjue: I submitted isys-vision/motoman#7 to add 6202cefd22759eadba9cd24052152a8fa513a0ab. Please review and merge.

2025-02-08 11:00 UTC, gavanderhoorn requested changes
Marking as *requested changes*.

2025-02-11 14:32 UTC, cjue commented
> @cjue: I submitted [isys-vision#7](https://github.com/isys-vision/motoman/pull/7) to add [6202cef](https://github.com/ros-industrial/motoman/commit/6202cefd22759eadba9cd24052152a8fa513a0ab). Please review and merge.

done

2025-02-13 12:17 UTC, gavanderhoorn approved these changes

2025-02-13 12:18 UTC, merged

2025-02-13 12:18 UTC, gavanderhoorn commented
Thanks @cjue :+1: