Add support for GP225 robot
ros-industrial/motoman pull request #583
Opened 2024-01-16 21:23 UTC by EricMarcil

Add support for Yaskawa Motoman GP225 robot

2025-01-31 13:08 UTC, gavanderhoorn requested changes

2025-01-31 13:08 UTC, gavanderhoorn commented on motoman_gp225_support/package.xml
> +      <li>GP225 - Default</li>
Similar to #607, the `xacro:macro` appears to model what *Table 5-1: Basic Specifications (YR-1-06VX225-A00)* labels as *Not-equipped*:

![image](https://github.com/user-attachments/assets/11d96ea1-f116-4484-adff-237db83bbe18)

Should we update this as well:

```suggestion
      <li>GP225 - Not-equipped</li>
```

?

2025-01-31 13:08 UTC, gavanderhoorn commented on motoman_gp225_support/package.xml
> +    </p>
This does not appear to be true for this package.

Copy-pasta?

2025-01-31 13:08 UTC, gavanderhoorn commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
This mesh gets rendered with an unexpected greenish washed out colour for me:

![rviz_screenshot_2025_01_31-14_07_04](https://github.com/user-attachments/assets/8dd20fb8-8a4d-40c2-9891-3b3eb4e95e90)

Should this not be black?

2025-02-12 09:40 UTC, gavanderhoorn commented
Friendly ping @EricMarcil

2025-02-17 21:20 UTC, EricMarcil commented on motoman_gp225_support/package.xml
> +    </p>
That is correct. It probably came from using another model as a base to build this one.

2025-02-17 22:52 UTC, EricMarcil commented on motoman_gp225_support/package.xml
> +      <li>GP225 - Default</li>
After further reflection, I don't think we should start doing equipped variant. The equipped variant has extra brackets and  cables running outside of the arm which is not included in the 3D model and I don't have the 3D models for that optional package. It is mainly for SpotWelding application which I don't think is used much among ROS users.

2025-02-17 23:00 UTC, EricMarcil commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
The yellow-greenish color is correct (it is some more resistant coating that is done on the flange). But there should be that much shadow, the original model surface lost it flatness probably too much downsampling. I found higher resolution of the same part on a different model but more details. I'll see if I can improve using that model tomorrow.

2025-02-23 03:12 UTC, cjue commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
I just added an opw config to my fork of this PR here:
https://github.com/isys-vision/motoman/tree/GP225

That branch is rebased to kinetic-devel as well.

One peculiar thing that I noticed:

The support structure that connects from link2 to link1 does not move as it would in reality, causing it (and the collision model of that link) to "protrude" in some joint angles, where actually it would stay connected to link1. 

I guess this can be ignored similarly to the cables attachments of many robots that are not realistically modeled, I just noticed it when checking the visual&collision meshes.
![Screenshot_20250223_035643_gp225_link2_attachment](https://github.com/user-attachments/assets/fa18b58e-ae46-4fb2-af64-c6951fcfb2d1)

https://www.yaskawa.eu.com/Global%20Assets/Downloads/Brochures_Catalogues/Robotics/MOTOMAN_Robots/GP-Series/Flyer_Robot_GP225_E_11.2020.pdf

2025-03-06 19:40 UTC, EricMarcil commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
@cjue I pushed a new commit in which the side balancer is moves using the urdf mimic option. It is not perfect, the real equation is non-linear (sin, cos elements) and the mimic function only support a linear function.  So, I had to linearize the function over the L-axis range. It gives an error of about +/- 2 degrees (about 20 mm) at the end of the motion range.

I also included it in the collision model, but those model will collide with each other, so maybe it would be better remove them.

2025-03-06 20:06 UTC, EricMarcil commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
![image](https://github.com/user-attachments/assets/24003dc9-d29d-4ca9-84a1-614e2245e31e)

2025-03-07 16:55 UTC, cjue commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
Wow, nice work!

I don't think the overlap of the two parts poses an issue, and the result is much better than the old version that could "poke out" at certain J2 angles.

One note for actual usage in MoveIt: it might be necessary to explicitly disable collision detection between link_1_s/link_2_s and both new links link_1_s_2 and link_2_s_2, and possible collisions of the two new links with each other (5 combinations total).

2025-03-07 16:57 UTC, cjue commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
I updated my fork of this PR to include your new commit, with the following additions
* add OPW config
* based on current ros-industrial/motoman kinetic-devel, while your branch is based on an older version
* remove trailing spaces in the urdf

https://github.com/isys-vision/motoman/tree/GP225

2025-03-07 16:58 UTC, cjue commented on motoman_gp225_support/urdf/gp225_macro.xacro
> +        <mimic joint="${prefix}joint_2_l" multiplier="0.7634"/>
trailing space

2025-03-07 16:58 UTC, cjue commented on motoman_gp225_support/urdf/gp225_macro.xacro
> +        <mimic joint="${prefix}joint_2_l" multiplier="-0.2366"/>
trailing space

2025-03-10 13:23 UTC, cjue commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
I opened a second PR in case it helps regarding the rebase issue:
https://github.com/ros-industrial/motoman/pull/619

2025-03-10 19:01 UTC, EricMarcil commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
@cjue 

> One note for actual usage in MoveIt: it might be necessary to explicitly disable collision detection between link_1_s/link_2_s and both new links link_1_s_2 and link_2_s_2, and possible collisions of the two new links with each other (5 combinations total).
That why I was wondering if we shouldn't simply remove  link_1_s_2 and link_2_s_2 from the collision model. But I guess end-users can make that decision.

2025-03-10 19:02 UTC, EricMarcil commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
> I opened a second PR in case it helps regarding the rebase issue: #619

I'm not sure of the rebase issue you are mentionning, but I'm fine with using the #619 since it already has you commits on it.

2025-03-11 10:02 UTC, cjue commented on motoman_gp225_support/meshes/gp225/visual/link_6_t.dae
@EricMarcil 

> That why I was wondering if we shouldn't simply remove link_1_s_2 and link_2_s_2 from the collision model. But I guess end-users can make that decision.

Now that I had another look at it: the collision model of link_2_l_2 appears to be completely inside of that of link_2_s, which is quite large because it also contains the cabling in that area. link_1_s_2 on the other hand is not fully redundant.

My proposal would therefore be to remove just link_2_l_2 from the collision model, which would reduce the extra collisions that might need to be manually disabled to just 2 instead of 5.

I added a commit for that to my fork.

2025-03-18 13:08 UTC, gavanderhoorn commented
Ok, so I took a look and I believe we've arrived at something we can merge.

@cjue: thanks for your updates and for #619. As @EricMarcil already had a PR and to not make things more complex than they need to be I've cleaned up the history a bit here and included the relevant commits from #619.

(note btw: 32628f57 technically broke the `xacro:macro`, as empty `collision` elements are not supported)

I'll wait for CI to finish and then we can merge.

2025-03-18 13:18 UTC, gavanderhoorn approved these changes

2025-03-18 13:39 UTC, gavanderhoorn commented
As this PR contains commits by multiple contributes we'll use a regular merge commit.

2025-03-18 13:39 UTC, merged

2025-03-18 13:39 UTC, gavanderhoorn commented
Thanks @EricMarcil and thanks again @cjue :+1: