HC20DTP and HC30PL Update
ros-industrial/motoman pull request #597
Opened 2024-08-15 15:40 UTC by EricMarcil

The HC20 package was updated with the HC20DTP and HC30PL variant. HC20 visual meshes were changed from .stl to .dae format to improve rendering.

2025-02-17 14:31 UTC, gavanderhoorn commented
High-level comment: could you please use multiple commits in future PRs when changing multiple things and adding support for new variants/series?

2025-02-17 14:42 UTC, EricMarcil commented
@gavanderhoorn Yes, I will try do split them up in the future.

2025-02-17 15:34 UTC, gavanderhoorn requested changes
Marking as *requested changes* while we discuss my comments.

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/package.xml
> +  <version>1.0.0</version>
We'll address this in a later PR, but we can't bump the version of this single package like this.

Catkin/Bloom limits things such that every package in a repository must have the same version.

Please revert this change and keep `version` at `0.1.0`.

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/package.xml
> +      which also supports the DT, XP, DTP and HC30PL variants.
we normally reserve this kind of phrasing for variants which don't get their own `xacro:macro`.

The DTP and 30PL do have their own `xacro:macro`, so I would recommend we change this to reflect that.

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/package.xml
> +      <li>HC30PL</li>
Seeing as we noticed there are actual variants of variants in other recently merged support packages: is there nothing we can state here as to which specific specification were used?

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc20dtp_macro.xacro
> +    </joint>
should we perhaps take this opportunity to add `flange` and `base` here?

Same comment for the 30PL below.

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="368.48" velocity="${radians(112)}"/>
Is this correct? 15 degrees only?

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="141.12" velocity="${radians(132)}"/>
same here

2025-02-17 15:34 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +        <origin rpy="0 1.57075 0"/>
why do these Collada meshes have a different orientation?

It would be nice to have the meshes aligned already, so as to simplify the `xacro:macro`.

Same comment for the `collision` of `link_5_b` and both meshes for `link_6_t`.

2025-02-21 21:43 UTC, EricMarcil commented on motoman_hc20_support/urdf/hc20dtp_macro.xacro
> +    </joint>
Yes, that is a good suggestion

2025-02-21 21:54 UTC, EricMarcil commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="368.48" velocity="${radians(112)}"/>
The HC30PL is an HC20 for Palletizing, so the wrist is always kept down.  This is what allows to manipulate 30 kg instead of 20 kg. But I'm realizing that the 15 deg in the manual is relative to the ground, not the previous link. For the R-axis, I believe that the 15 deg is correct because it doesn't combine with other axes.

2025-02-21 21:55 UTC, EricMarcil commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="141.12" velocity="${radians(132)}"/>
The HC30PL is an HC20 for Palletizing, so the wrist is always kept down. This is what allows to manipulate 30 kg instead of 20 kg. But I'm realizing that the 15 deg in the manual is relative to the ground, not the previous link. The B-axis range probably needs to be reviewed to allow more motion. I don't think there is any way to put at restriction on the B-axis by considering the other axes current position.

2025-02-21 22:06 UTC, EricMarcil commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +        <origin rpy="0 1.57075 0"/>
Because the HC30PL cannot have the B-axis in the horizontal position, so its zero position is with the wrist pointing down. I didn't want add an extra collada mesh just to turn it 90 degrees when it can be done here inthe xacro.

2025-02-21 22:07 UTC, EricMarcil commented on motoman_hc20_support/package.xml
> +  <version>1.0.0</version>
Ok, I didn't realize that it was impacting other things. We can revert.

2025-03-18 13:42 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="368.48" velocity="${radians(112)}"/>
hm. As we don't have any way to model these kinds of constraints (`joint` limits are always relative to parent `joint`s/`link`s), I'm wondering what the best course of action would be.

2025-03-18 13:43 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="141.12" velocity="${radians(132)}"/>
> I don't think there is any way in a URDF to put at motion restriction on the B-axis relative to the ground or by considering the other axes current position.

no, there currently isn't. See my previous comment.

2025-03-18 13:44 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +        <origin rpy="0 1.57075 0"/>
Ok, that makes sense. Thanks for clarifying. We could perhaps add your comment to the `xacro:macro` as a comment.

2025-03-18 13:44 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc20dtp_macro.xacro
> +    </joint>
@EricMarcil: would you be able to to add those `link`s?

2025-03-26 15:46 UTC, EricMarcil commented on motoman_hc20_support/package.xml
> +  <version>1.0.0</version>
Reverted to 0.1.0

2025-03-26 15:48 UTC, EricMarcil commented on motoman_hc20_support/package.xml
> +      which also supports the DT, XP, DTP and HC30PL variants.
CHanged to:
This package contains configuration data, 3D models and launch files for Motoman HC20, HC20DTP and HC30PL manipulators. The HC20 base model also includes the DT, XP variants.

2025-03-26 15:56 UTC, EricMarcil commented on motoman_hc20_support/package.xml
> +      <li>HC30PL</li>
For those robots, there are only one version specified in the referenced manuals for each model.

2025-03-26 15:57 UTC, EricMarcil commented on motoman_hc20_support/urdf/hc20dtp_macro.xacro
> +    </joint>
Added for all HC20, HC20DTP and HC30PL

2025-03-26 16:00 UTC, EricMarcil commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="141.12" velocity="${radians(132)}"/>
The B-axis range was increased back to +/-180 deg. I added a note about it in the package.xml:
```
       NOTE: The HC30PL is the palletizing variant of the HC20 where the 
      wrist must always point toward the ground +/-15 degrees, which allows 
      a greater payload of 30 kg. There is no way of building this constraint
      in the urdf model. Therefore, this constraint will need to be handled 
      explicitly by the motion planner.
```

2025-03-26 16:36 UTC, cjue commented
In our repo we had added (identical) opw configs for HC20 DT and HC20 DTP:

https://github.com/isys-vision/motoman/commit/f2f4c61176f787a7a907aeead063e6859dfc1e55

We also renamed the hc20 files to hc20dt, which you probably don't want to copy:

https://github.com/isys-vision/motoman/commit/f10f3e612f21da1a93672537decd523a99db8fcb

2025-03-26 17:17 UTC, EricMarcil commented
@cjue I've added the opw_parameters files based on your files. Can you please double check the one for the hc30pl that I added. I believe that the -90 offset for the 5th joint is the only change required.

2025-03-31 15:37 UTC, cjue commented
> @cjue I've added the opw_parameters files based on your files. Can you please double check the one for the hc30pl that I added. I believe that the -90 offset for the 5th joint is the only change required.

MoveIt accepts the opw config for the HC30 PL, I could move the robot and the OPW file is correct as it corresponds to the URDF file.

About the HC30 urdf file:

> The B-axis range probably needs to be reviewed to allow more motion, because the L and U axes are working in the same plane

Can you explain that a bit more? Currently the URDF in the PR allows +/-15° for joint_4_r, matching the [datasheet](https://www.yaskawa.eu.com/Global%20Assets/Downloads/Brochures_Catalogues/Robotics/MOTOMAN_Robots/HC30PL/Flyer_Cobot_HC30PL_E.pdf), while allowing +/- 180° for joint_5_b, where the datasheet would also dictate +/-15°.

Won't the controller abort any trajectory that moves outside the +/- 15 ° range for J5?

2025-03-31 16:22 UTC, EricMarcil commented
The +/- 15 degrees is relative to the floor.
This is an example where the B-axis is within its 15 degrees limits relative to the floor, but the B-axis position relative to the previous joint is around 217 deg

![image](https://github.com/user-attachments/assets/8692e756-e9fb-4efb-9529-01ebae875c8b)

But you are correct, I'll need to correct the B-axis range. I forgot to account for the 90 deg offset. So the range is -90 to 270.

2025-03-31 16:43 UTC, EricMarcil commented
I've updated the hc30pl based on the limits from the parameter files. So the new values will be correct.

The user will need to insure that the robot flange remains +/- 15 degrees relative to the ground.

I haven't tested in MotoRos but normally the controller will give an alram 4420 SPECIAL SOFTLIMIT [R1: MAX B] at execution time when the robot is commanded to move outside of the 15 deg position.

2025-04-03 10:30 UTC, cjue commented
Sounds reasonable :+1: 

It's quote confusing that the datasheet differs this much from the URDF and the parameter files without specifying that the +/- 15° constraint is relative to the floor.

2025-04-10 12:59 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="141.12" velocity="${radians(132)}"/>
'the wrist' means both `joint_4_r` and `joint_5_b`, correct?

2025-04-10 13:07 UTC, gavanderhoorn commented on motoman_hc20_support/urdf/hc30pl_macro.xacro
> +      <limit lower="${radians(-15)}" upper="${radians(15)}" effort="141.12" velocity="${radians(132)}"/>
Assuming *yes*, I've added 83a611a308563f715264dddf42333bb76d8fe012.

2025-04-10 13:24 UTC, gavanderhoorn commented on motoman_hc20_support/config/opw_parameters_hc20dtp.yaml
> +    b:   0.000
@EricMarcil @cjue: before e7a2ee7d this read `-0.0`. I'm assuming that was copy-pasta and removed the `-` sign.

2025-04-10 13:29 UTC, cjue commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
I understand this constraint to mostly limit the wrist / tool0 / flange orientation as a combination of joint_4_r and joint_5_b.

```suggestion
      NOTE: the HC30PL is the palletizing variant of the HC20 where the wrist
      joints ('joint_4_r' and 'joint_5_b') are constrained to orient the flange to 
      within +/-15 degrees with respect to the ground plane normal.
```

2025-04-10 13:33 UTC, gavanderhoorn commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
given the zero pose of those two joints is aligned with the ground plane normal, would there be a difference?

I'm also not sure we can orient a surface in the way you describe. We'd either have to align the two normals -- ground plane and flange normal -- or say something about the flange surface having to be orthogonal to the ground plane normal, which isn't really clear.

2025-04-10 13:35 UTC, cjue commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
You're right, I clarified that the `flange normal` is to be aligned to the ground plane normal.

```suggestion
      NOTE: the HC30PL is the palletizing variant of the HC20 where the wrist
      joints ('joint_4_r' and 'joint_5_b') are constrained to orient the flange normal 
      to within +/-15 degrees with respect to the ground plane normal.
```

2025-04-10 14:17 UTC, gavanderhoorn commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
as I wrote, as the zero pose of the joints already causes the flange normal to be aligned with the ground plane normal, I believe it'd be ok to say something about the joint limits -- which is easier to understand I believe than surface normals.

2025-04-10 15:49 UTC, ted-miller commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
I'm ok with cjue's wording.

2025-04-10 16:06 UTC, EricMarcil commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
I think it is ok. Otherwise, it would be: the 'joint_4_r' and the combination of 'joint_2_l', 'joint_3_u' and 'joint_5_b' are constrained to orient the flange normal to within +/-15 degrees with respect to the ground plane normal.

2025-04-10 18:07 UTC, gavanderhoorn commented on motoman_hc20_support/package.xml
> +      respect to the ground plane normal.
Ok. We'll merge it then.

2025-04-10 18:17 UTC, gavanderhoorn approved these changes

2025-04-10 18:18 UTC, merged

2025-04-10 18:18 UTC, gavanderhoorn commented
Thank you @EricMarcil for the updates and thanks @cjue for the additional comments and contributions :+1: