test_<model>.launch files update
ros-industrial/motoman pull request #600
Opened 2024-09-24 20:54 UTC by EricMarcil

Changed the test_<model>.launch files to use the "joint_state_publisher_gui" instead of the "joint_state_publisher" so that the joint slide controls are displayed with RViz.

2024-09-26 08:04 UTC, gavanderhoorn requested changes
It won't make CI green for Kinetic or Melodic, but if we change this, we must update the `package.xml` to state the dependency on `joint_state_publisher_gui` (instead of the current `joint_state_publisher`).

2024-10-09 19:53 UTC, EricMarcil commented
@gavanderhoorn Updated the package,xml files dependency

2025-01-31 12:58 UTC, gavanderhoorn commented
I'll take another look at this one after the PRs contributing more robot support packages have been merged.

2025-02-17 11:01 UTC, gavanderhoorn commented
@EricMarcil: I've merged your two commits into one (bcd4d892a6ad458e6e35efa71a08c598e0f92677 was a fixup of the real fix) and corrected some minor issues.

We'll wait for green CI and then merge.

2025-02-17 14:06 UTC, gavanderhoorn approved these changes

2025-02-17 14:06 UTC, merged

2025-02-17 14:06 UTC, gavanderhoorn commented
Thanks @EricMarcil :+1: