Add GP20HL robot support package
ros-industrial/motoman pull request #604
Opened 2024-10-09 20:03 UTC by EricMarcil

Add GP20HL robot support package

2025-01-31 12:17 UTC, gavanderhoorn requested changes
`link_6_t.dae` needs to be fixed.

2025-01-31 12:17 UTC, gavanderhoorn commented on motoman_gp20hl_support/meshes/gp20hl/visual/link_6_t.dae
this file appears to be 'empty' (as in: there's no mesh data defined here).

2025-01-31 12:17 UTC, gavanderhoorn commented on motoman_gp20hl_support/config/opw_parameters_gp20hl.yaml
Have these values been verified?

2025-01-31 13:23 UTC, gavanderhoorn commented
@EricMarcil: I just noticed #566.

Is this a copy of that PR?

2025-01-31 13:29 UTC, EricMarcil commented on motoman_gp20hl_support/config/opw_parameters_gp20hl.yaml
No, there are based on the definition from [opw_kinematics_tutorial.rst](https://github.com/moveit/moveit_tutorials/blob/master/doc/opw_kinematics/opw_kinematics_tutorial.rst)

And reviewing them, the a2 value should be negative.

It is untested. We could remove if you prefer.

2025-01-31 13:39 UTC, gavanderhoorn commented on motoman_gp20hl_support/config/opw_parameters_gp20hl.yaml
Adding OPW parameters is a good thing, but we should make sure the values are correct.

I'm not sure how easy that would be though. I only know of `JeroenDM/moveit_opw_kinematics_plugin` and that needs a MoveIt configuration.

2025-01-31 13:40 UTC, EricMarcil commented
No, it

> @EricMarcil: I just noticed #566.
> 
> Is this a copy of that PR?

No, it is a new one that I made. I must have missed the #566 that was made by [acbuynak](https://github.com/acbuynak).
I used the MotoSim model to generate the visual meshes in .dae which keeps the colors of the orignial model. So, I would prefer to keep this one.

2025-01-31 14:07 UTC, gavanderhoorn commented on motoman_gp20hl_support/config/opw_parameters_gp20hl.yaml
> And reviewing them, the a2 value should be negative.

Fixed in b195458539fdd8353d03047547e8beca9328dc41.

Clarified status in 99c26e1fd6161027bef64c0c39cf4810ded4cd38.

2025-02-04 14:34 UTC, EricMarcil commented on motoman_gp20hl_support/meshes/gp20hl/visual/link_6_t.dae
Oops, the model must not have been selected when I exported it and I didn't noticed. 
I just committed an update of the model.

2025-02-07 16:52 UTC, gavanderhoorn approved these changes

2025-02-07 16:52 UTC, merged

2025-02-07 16:52 UTC, gavanderhoorn commented
Thanks @EricMarcil :+1: